---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kyma-system
  labels:
    "services.cloud.sap.com/managed-by-sap-btp-operator": "true"
data:
  CLUSTER_ID: 105f5611-2dbe-4d3a-9f8b-39d501c1a7b1
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  ENABLE_LIMITED_CACHE: "true"
  ALLOW_CLUSTER_ACCESS: "true"
